# Generated by Django 4.0.2 on 2022-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_contact_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'Facebook'), (3, 'Email')]),
        ),
    ]
