# Generated by Django 4.0.2 on 2022-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_imgpath_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='suit',
            field=models.CharField(choices=[(1, 'Phone'), (2, 'Facebook'), (3, 'Email')], max_length=50),
        ),
    ]
